[package]
name = "openAI_cli_chatbog_codetothemoon_tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = {version = "^0.14", features = ["full"]}
hyper-tls = "^0.5" #need to utilize tls cargo package to access HTTPS connectors, as OpenAI's API uses HTTPS
tokio = {version = "1", features = ["full"]}
serde = {version="^1", features = ["derive"]}
#serde_derive = "^1"
serde_json = "^1"
spinners = "4"
dotenvy = "0.15.7"